language: python
install:
  - pip install -e .
  - df -h
script: py.test

python:
    - "3.7"

matrix:
  include:
    - python: "3.7"
      dist: focal
      sudo: true
    - python: "3.7"
      arch: arm64
      dist: focal
      sudo: true
    - python: "3.7"
      os: linux
      dist: focal
      group: edge
      arch: arm64-graviton2
      virt: lxd
      sudo: true
