language: python
install: pip install -e .
script: py.test

python:
    - "3.6"

matrix:
  include:
    - python: "3.7"
      dist: bionic
      sudo: true
    - python: "3.7"
      arch: arm64
      dist: bionic
      sudo: true
    - python: "3.7"
      os: linux
      dist: bionic
      group: edge
      arch: arm64-graviton2
      virt: lxd
      sudo: true
